steps:
 name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
 entrypoint: 'bash'
 args:
 - '-c'
   |
   gcloud run deploy python-app \
     --image northamerica-northeast2-docker.pkg.dev/cool-keel-408219/assignment3/dumy-image:$COMMIT_SHA \
     --region-northamerica-northeast2 \
     --port=3000 \
     --platform-managed \
     --allow-unauthenticated \
     --vpc-connector-zainab-vpc-connector

 options:
  defaultLogsBucketBehavior : REGIONAL_USER_OWNED_BUCKET
    
